### ISSUE TITLE
CANNOT export to clipboard

### ISSUE THREAD

**Issue by bilibili20001** [juliuskreutz/stardb-exporter#1]
My game is Asia Server.
I followed the tips and when it showed "All ready", I went into hyperspeed, and nothing happened.
Here is the screenshot.
![20240604193916](https://github.com/juliuskreutz/stardb-exporter/assets/70944645/fab7dd19-3003-4aa5-9e12-4e2814330369)
Could you please help me?
Thanks.

**Comment by juliuskreutz** [comment]
Hi! Yeah sure.
Do you happen to have discord? You could join the [stardb discord](https://discord.gg/chives) and ping me in any channel and I'll try to help you

**Comment by bilibili20001** [comment]
> Hi! Yeah sure. Do you happen to have discord? You could join the [stardb discord](https://discord.gg/chives) and ping me `@julisus` in any channel and I'll try to help you

It seems that I didn't tick `Support raw 802. 11 traffic (and monitor mode) for wireless adapters` while installing Npcap, cuz I'm using WiFi.
Or there may be some problems in the network in China.
Now I solved the problem and exported my achievements simply.
Thank you very much!
![20240605192300](https://github.com/juliuskreutz/stardb-exporter/assets/70944645/f56ab667-7560-4b0d-8f8a-821cbba34de8)
