### ISSUE TITLE
Cannot collect stats while using a VPN

### ISSUE THREAD

**Issue by LightArrowsEXE** [juliuskreutz/stardb-exporter#3]
When running a VPN, the program will seemingly not be able to collect stats.

## Steps to Reproduce

1. turn on a VPN
2. follow steps as provided in the README

I'm not sure this is something that you can work around, so perhaps it's a good idea to mention this in the README. This also occurs with other importers that read packets in the loading screen, such as the [reliquary-archiver](https://github.com/IceDynamix/reliquary-archiver).

**Comment by juliuskreutz** [comment]
I will put that into the README for now until maybe I find a fix for this.
