### ISSUE TITLE
NOT working on HSR 2.5

### ISSUE THREAD

**Issue by bilibili20001** [juliuskreutz/stardb-exporter#6]
thread 'main' panicked at C:\Users\runneradmin\.cargo\git\checkouts\reliquary-c3aaa60f88a6d68e\7a74ef3\src\network\crypto.rs:39:22:
unknown key for version 2057675565
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
![20240911203457](https://github.com/user-attachments/assets/8231af50-840b-4bf0-ae3b-48244627b0f4)

**Comment by qihangL** [comment]
same issue here

**Comment by juliuskreutz** [comment]
Should work now :D
