### ISSUE TITLE
`Option::unwrap` failed while importing genshin achievements

### ISSUE THREAD

**Issue by FichteFoll** [juliuskreutz/stardb-exporter#7]
```
~/code/#mirror/stardb-exporter ж cargo run --release
    Finished `release` profile [optimized] target(s) in 0.19s
     Running `target/release/stardb-exporter`
Checking target-arch... x86_64-unknown-linux-gnu
Checking current version... v2.1.0
Checking latest released version... v2.1.0
thread '<unnamed>' panicked at /home/fichte/.cargo/git/checkouts/artifactarium-bd83d35112a48240/26ab326/src/network/mod.rs:291:57:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

version: https://github.com/juliuskreutz/stardb-exporter/commit/665790866a4edd29f5d9cfae1ad86a2e29436109
os: arch linux

I can also rerun with the backtrace and also a debug built tomorrow, if that helps

**Comment by Deximo** [comment]
Same on Windows OS stuck on Running status

![Screenshot 2024-10-10 183511](https://github.com/user-attachments/assets/a1fbdf01-d315-4515-bf7c-9ae8915c9233)

**Comment by juliuskreutz** [comment]
I am sadly at the mercy of datamined protobufs, to read the incoming network requests. After an update it will always take a little while until it will work again. I'll add a better error message though!

**Comment by FichteFoll** [comment]
Oh right, I forgot that GI support was added last week and not yesterday when I found out about it. :sweat_smile: I know the procedure from rqa but didn't connect the dots.

Perhaps you could detect whether the protocol has been updated with a game patch and is now incompatible with the application to show a more detailed error that the exporter needs to be updated? I'm sure you've seen this happen with almost every patch for hsr already.

**Comment by juliuskreutz** [comment]
Yes. The change to an actual ui happened a few days ago (It was a simple cli before). I'm still adding and optimizing things on the fly

**Comment by juliuskreutz** [comment]
Fixed
