### ISSUE TITLE
Error: environment variable not found

### ISSUE THREAD

**Issue by FichteFoll** [juliuskreutz/stardb-exporter#8]
Trying to use any of the "import pull history" buttons always yields the text "Error: environment variable not found" for me, but I found no mention of the environment variable I need to set in the README. Since I'm playing on Linux, I imagine I need to tell it where my game folders are (so that it can extract the URL from the respective `data_2` file), but some documentation on that would be appreciated.

**Comment by juliuskreutz** [comment]
I'm working on something for the linux part :D. You'll have to wait a bit though, sorry

**Comment by juliuskreutz** [comment]
I have decided! I'll try to get it done today!

**Comment by FichteFoll** [comment]
(No rush about the history import on my part, since I have shell scripts to extract the URL for me, but feel free to use it as a motivation regardless. I was just curious what the buttons did when I wanted to try out the new achievement export.)

**Comment by juliuskreutz** [comment]
I have implemented something. Will make it better in the next version but it works for now :D

**Comment by FichteFoll** [comment]
For the record, manually selecting the game data folder worked.
